{{- $host := .Values.ingress.web.hostname | default .Values.ingress.hostname -}}
{{- if and .Values.ingress.enabled $host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "farm.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "farm.web.labels" . | nindent 4 }}
  {{- with merge (dict) (.Values.ingress.web.annotations | default dict) (.Values.ingress.annotations | default dict) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
          {{- range .Values.ingress.web.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "farm.fullname" $ }}-web
                port:
                  number: {{ $.Values.web.service.port }}
          {{- end }}
{{- end }}
