{{- if and .Values.api.podDisruptionBudget.enabled (gt (int .Values.api.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "farm.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "farm.api.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "farm.api.selectorLabels" . | nindent 6 }}
{{- end }}
