{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "farm.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "farm.web.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.web.hostname }}
      secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-web-tls" (include "farm.fullname" .)) }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.web.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "farm.fullname" . }}-web
                port:
                  number: {{ .Values.web.service.port }}
{{- end }}
