{{- if .Values.web.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "farm.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "farm.web.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.web.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "farm.web.selectorLabels" . | nindent 6 }}
{{- end }}
